// const products = [
//     {
//         _id: '1',
//         name: 'Second Wife Resturant',
//         image: '/images/secondwife.jpg',
//         dishesList: "Mutton Koyla Karahi , Chicken Koyla Karahi , Pizza , Fast Food , Bar B Q , Chinese , Roll , Rice and Noodles , Paratha , Starters and Salads , Burgers , Desserts , Sides Orders , Beverages",
//         ratedDishes: "",
//         description:
//             'aa',
//         brand: 'Apple',
//         category: 'Electronics',
//         price:89 ,
//         countInStock: true,
//         rating: 2.5,
//         numReviews : 4,
//     },
//     {
//         _id: '2',
//         name: 'Al-Basit Resturant',
//         image: '/images/albasit.jpg',
//         dishesList: "Mutton Koyla Karahi , Chicken Koyla Karahi , Pizza , Fast Food , Bar B Q , Chinese , Roll , Rice and Noodles , Paratha , Starters and Salads , Burgers , Desserts , Sides Orders , Beverages",
//         ratedDishes: "",
//         description:
//             'aa',
//         brand: 'Apple',
//         category: 'Electronics',
//         price:89 ,
//         countInStock: 3,
//         rating: 4.5,
//         numReviews : 4,
//     },
//     {
//         _id: '3',
//         name: 'King Broast Resturant',
//         image: '/images/kingbroast.jpg',
//         dishesList: "Mutton Koyla Karahi , Chicken Koyla Karahi , Pizza , Fast Food , Bar B Q , Chinese , Roll , Rice and Noodles , Paratha , Starters and Salads , Burgers , Desserts , Sides Orders , Beverages",
//         ratedDishes: "",
//         description:
//             'aa',
//         brand: 'Apple',
//         category: 'Electronics',
//         price:89 ,
//         countInStock: 3,
//         rating: 4.5,
//         numReviews : 4,
//     },
//     {
//         _id: '4',
//         name: 'Lucky Broast Resturant',
//         image: '/images/luckybroast.jpg',
//         dishesList: "Mutton Koyla Karahi , Chicken Koyla Karahi , Pizza , Fast Food , Bar B Q , Chinese , Roll , Rice and Noodles , Paratha , Starters and Salads , Burgers , Desserts , Sides Orders , Beverages",
//         ratedDishes: "",
//         description:
//             'aa',
//         brand: 'Apple',
//         category: 'Electronics',
//         price:89 ,
//         countInStock: 3,
//         rating: 4.5,
//         numReviews : 4,
//     },
//     {
//         _id: '5',
//         name: 'King Broast Resturant',
//         image: '/images/kingbroast.jpg',
//         dishesList: "Mutton Koyla Karahi , Chicken Koyla Karahi , Pizza , Fast Food , Bar B Q , Chinese , Roll , Rice and Noodles , Paratha , Starters and Salads , Burgers , Desserts , Sides Orders , Beverages",
//         ratedDishes: "",
//         description:
//             'aa',
//         brand: 'Apple',
//         category: 'Electronics',
//         price:89 ,
//         countInStock: 3,
//         rating: 4.5,
//         numReviews : 4,
//     },
//     {
//         _id: '6',
//         name: 'Lucky Broast Resturant',
//         image: '/images/luckybroast.jpg',
//         dishesList: "Mutton Koyla Karahi , Chicken Koyla Karahi , Pizza , Fast Food , Bar B Q , Chinese , Roll , Rice and Noodles , Paratha , Starters and Salads , Burgers , Desserts , Sides Orders , Beverages",
//         ratedDishes: "",
//         description:
//             'aa',
//         brand: 'Apple',
//         category: 'Electronics',
//         price:89 ,
//         countInStock: 3,
//         rating: 4.5,
//         numReviews : 4,
//     }

// ]
// export default products;