// export const CART_ADD_ITEM = 'CART_ADD_ITEM'
// export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
// export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
// export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'



export const BAG_ADD_ITEM = 'BAG_ADD_ITEM'
export const BAG_REMOVE_ITEM = 'BAG_REMOVE_ITEM'
export const BAG_SAVE_SHIPPING_ADDRESS = 'BAG_SAVE_SHIPPING_ADDRESS'
export const BAG_SAVE_SHIPPING_LOCATION= 'BAG_SAVE_SHIPPING_LOCATION'
export const BAG_SAVE_PAYMENT_METHOD = 'BAG_SAVE_PAYMENT_METHOD'
